DO
$$
BEGIN
    IF
NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'crm_app') THEN
CREATE ROLE crm_app LOGIN PASSWORD 'CrmLab_Strong1';
ELSE
        ALTER
ROLE crm_app WITH LOGIN PASSWORD 'CrmLab_Strong1';
END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS crm_app AUTHORIZATION crm_app;

REVOKE ALL ON SCHEMA public FROM crm_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM crm_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM crm_app;
REVOKE CREATE ON SCHEMA public FROM crm_app;
REVOKE USAGE ON SCHEMA public FROM crm_app;

ALTER
ROLE crm_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT
ON DATABASE crm TO crm_app;
GRANT USAGE, CREATE
ON SCHEMA crm_app TO crm_app;